[project]
name = "hn-rerank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "numpy>=2.4.0",
    "onnxruntime>=1.23.2",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.10",
    "scikit-learn>=1.8.0",
    "textual>=7.0.0",
    "trafilatura>=2.0.0",
    "transformers>=4.57.3",
]
